# Generated by Django 2.2.7 on 2020-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimg',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
