# Generated by Django 2.2.7 on 2020-05-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_postimg_imgname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Postimg',
        ),
    ]
